[{"type": "GitHub Fetch Error", "message": "name 'API_URL' isn't defined", "details": "Traceback (most recent call last):\n  File \"<stdin>\", line 205, in fetch_from_github\nNameError: name 'API_URL' isn't defined\n", "source": "fetch_from_github", "timestamp": "2024-12-03 07:46:13"}, {"type": "Main Loop Error", "message": "'module' object has no attribute 'path'", "details": "Traceback (most recent call last):\n  File \"<stdin>\", line 259, in main\nAttributeError: 'module' object has no attribute 'path'\n", "source": "main.py", "timestamp": "2024-12-03 07:46:13"}, {"type": "GitHub Fetch Error", "message": "-2", "details": "Traceback (most recent call last):\n  File \"<stdin>\", line 258, in fetch_from_github\n  File \"requests/__init__.py\", line 201, in get\n  File \"requests/__init__.py\", line 79, in request\nOSError: -2\n", "source": "fetch_from_github", "timestamp": "2024-12-03 07:53:14"}, {"type": "Download Error", "message": "", "details": "Traceback (most recent call last):\n  File \"<stdin>\", line 141, in download_file\n  File \"requests/__init__.py\", line 28, in text\nUnicodeError: \n", "source": "download_file", "timestamp": "2024-12-03 08:00:34"}, {"unix_timestamp": 1733213741, "type": "Download Error", "message": "", "formatted_time": "2024-12-03 08:15:41", "source": "download_file", "details": "Traceback (most recent call last):\n  File \"<stdin>\", line 143, in download_file\n  File \"requests/__init__.py\", line 28, in text\nUnicodeError: \n"}, {"source": "download_file", "type": "Download Error", "message": "", "formatted_time": "2024-12-03 08:47:03", "details": "Traceback (most recent call last):\n  File \"<stdin>\", line 143, in download_file\n  File \"requests/__init__.py\", line 28, in text\nUnicodeError: \n", "unix_timestamp": 1733215623}, {"details": "Traceback (most recent call last):\n  File \"<stdin>\", line 267, in fetch_from_github\n  File \"requests/__init__.py\", line 201, in get\n  File \"requests/__init__.py\", line 79, in request\nOSError: -2\n", "type": "GitHub Fetch Error", "message": "-2", "formatted_time": "2024-12-03 09:16:49", "unix_timestamp": 1733217409, "source": "fetch_from_github"}, {"unix_timestamp": 1733217914, "type": "Download Error", "message": "", "formatted_time": "2024-12-03 09:25:14", "source": "download_file", "details": "Traceback (most recent call last):\n  File \"<stdin>\", line 143, in download_file\n  File \"requests/__init__.py\", line 28, in text\nUnicodeError: \n"}, {"source": "download_file", "type": "Download Error", "message": "", "formatted_time": "2024-12-03 12:10:52", "details": "Traceback (most recent call last):\n  File \"<stdin>\", line 143, in download_file\n  File \"requests/__init__.py\", line 28, in text\nUnicodeError: \n", "unix_timestamp": 1733227852}, {"details": "Traceback (most recent call last):\n  File \"<stdin>\", line 154, in download_file\n  File \"requests/__init__.py\", line 28, in text\nUnicodeError: \n", "type": "Download Error", "message": "", "formatted_time": "2024-12-03 14:41:53", "unix_timestamp": 1733236913, "source": "download_file"}, {"unix_timestamp": 1733237649, "type": "Download Error", "message": "", "formatted_time": "2024-12-03 14:54:09", "source": "download_file", "details": "Traceback (most recent call last):\n  File \"<stdin>\", line 187, in download_file\n  File \"requests/__init__.py\", line 28, in text\nUnicodeError: \n"}, {"source": "download_file", "type": "Download Error", "message": "", "formatted_time": "2024-12-03 15:11:33", "details": "Traceback (most recent call last):\n  File \"<stdin>\", line 187, in download_file\n  File \"requests/__init__.py\", line 28, in text\nUnicodeError: \n", "unix_timestamp": 1733238693}, {"details": "Traceback (most recent call last):\n  File \"<stdin>\", line 143, in download_file\n  File \"requests/__init__.py\", line 28, in text\nUnicodeError: \n", "type": "Download Error", "message": "", "formatted_time": "2024-12-03 15:19:50", "unix_timestamp": 1733239190, "source": "download_file"}]