[{"details": "Traceback (most recent call last):\n  File \"main.py\", line 164, in download_file\n  File \"requests/__init__.py\", line 28, in text\nUnicodeError: \n", "type": "Download Error", "message": "", "formatted_time": "2021-01-01 00:00:27", "unix_timestamp": 1609459227, "source": "download_file"}]