[{"type": "GitHub Fetch Error", "message": "name 'API_URL' isn't defined", "details": "Traceback (most recent call last):\n  File \"<stdin>\", line 205, in fetch_from_github\nNameError: name 'API_URL' isn't defined\n", "source": "fetch_from_github", "timestamp": "2024-12-03 07:46:13"}, {"type": "Main Loop Error", "message": "'module' object has no attribute 'path'", "details": "Traceback (most recent call last):\n  File \"<stdin>\", line 259, in main\nAttributeError: 'module' object has no attribute 'path'\n", "source": "main.py", "timestamp": "2024-12-03 07:46:13"}, {"type": "GitHub Fetch Error", "message": "-2", "details": "Traceback (most recent call last):\n  File \"<stdin>\", line 258, in fetch_from_github\n  File \"requests/__init__.py\", line 201, in get\n  File \"requests/__init__.py\", line 79, in request\nOSError: -2\n", "source": "fetch_from_github", "timestamp": "2024-12-03 07:53:14"}]